version: "3.8"
services:
  database:
    image: mysql:8
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: